######################################################################
# Automatically generated by qmake (2.01a) Mi Apr 4 20:52:28 2007
######################################################################

TEMPLATE = app
TARGET = swetest

LIBS          	+= -L.. -L../release -lswe
DEPENDPATH 	+= ..
INCLUDEPATH	+= ..

# Input
HEADERS 	+= swephexp.h

SOURCES 	+= swetest.c

CONFIG += release
CONFIG -= qt

